---
kind: pipeline
name: runner
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: deploy-runner
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - apk add -U curl git
      - git fetch origin
      - git reset --hard origin/$${BRANCH}
      - git checkout $${BRANCH}
      - bin/runner/run.sh
    environment:
      ACTION: deploy
      BRANCH: main
      KUBE_TOKEN_ACP_NOTPROD:
        from_secret: forms-runner-kube-token
      KUBE_TOKEN_ACP_PROD:
        from_secret: kube_token_acp_prod
      KUBE_TOKEN_ACP_TEST:
        from_secret: kube_token_acp_test
      PREVIEW_MODE: true
      GOV_UK_NOTIFY_DEFAULT_API_KEY:
        from_secret: NOTIFY_API_KEY
      GOV_UK_NOTIFY_DEFAULT_TEMPLATE_ID:
        from_secret: NOTIFY_TEMPLATE_ID
      IMAGE_URL: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/forms-runner
    when:
      event:
        - promote
  - name: slack-notification-runner-deployed
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: stp-formbuilder-alerts
      template: >
        {{#success build.status}}
          runner deployment successful. Good job.
          Environment: {{build.deployTo}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{else}}
          runner deployment failed. Fix me please.
          Environment: {{build.deployTo}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{/success}}
    when:
      event:
        - promote
      status:
        - success
        - failure
    depends_on:
      - deploy-runner

---
kind: pipeline
name: designer
type: kubernetes

platform:
  os: linux
  arch: amd64
steps:
  - name: deploy-designer
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - apk add -U curl git
      - git fetch origin
      - git reset --hard origin/$${BRANCH}
      - git checkout $${BRANCH}
      - bin/designer/run.sh
    environment:
      ACTION: deploy
      BRANCH: main
      IMAGE_URL: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/forms-designer
      KUBE_TOKEN_ACP_NOTPROD:
        from_secret: forms-designer-kube-token
      PREVIEW_MODE: true
      PREVIEW_URL: https://runner-preview.dev.stp-forms-notprod.homeoffice.gov.uk
      PUBLISH_URL: https://runner-preview.dev.internal.stp-forms-notprod.homeoffice.gov.uk
    when:
      event:
        - promote
  - name: slack-notification-designer-deployed
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: stp-formbuilder-alerts
      template: >
        {{#success build.status}}
          designer deployment successful. Good job.
          Environment: {{build.deployTo}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{else}}
          designer deployment failed. Fix me please.
          Environment: {{build.deployTo}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{/success}}
    when:
      event:
        - promote
      status:
        - success
        - failure
    depends_on:
      - deploy-designer

---
kind: pipeline
name: smoke-tests
type: kubernetes
platform:
  os: linux
  arch: amd64
steps:
  - name: checkout code from xgov
    image: alpine/git
    commands:
      - git clone https://github.com/XGovFormBuilder/digital-form-builder/
      - cd digital-form-builder
      - git fetch --all --tags
      - export TAG=${DESIGNER_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)}
      - echo "TAG=$TAG"
      - git checkout tags/$TAG -b smoketests
      - cd ..
  - name: setup app url
    pull: if-not-exists
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
    commands:
      - echo ${DRONE_DEPLOY_TO}
      - if ${DRONE_DEPLOY_TO}=='test' (export ST_ENV='dev') else (export ST_ENV='test')
      - export APP_URL=https://designer.${ST_ENV}.stp-forms-notprod.homeoffice.gov.uk
      - echo ${APP_URL}
    depends_on:
      - checkout code from xgov
  - name: smoke-tests
    pull: if-not-exists
    image: node:12.18.4-buster
    commands:
      - cd digital-form-builder/smoke-tests/designer/
      - yarn
      - yarn smoke-test-headless
    depends_on:
      - setup app url
depends_on:
  - designer
  - runner
