---
kind: pipeline
name: runner
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: deploy-runner
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - apk add -U curl git
      - git fetch origin
      - git reset --hard origin/$${BRANCH}
      - git checkout $${BRANCH}
      - bin/runner/run.sh
    environment:
      ACTION: deploy
      BRANCH: main
      KUBE_TOKEN_ACP_NOTPROD:
        from_secret: forms-runner-kube-token
      KUBE_TOKEN_ACP_PROD:
        from_secret: kube_token_acp_prod
      KUBE_TOKEN_ACP_TEST:
        from_secret: kube_token_acp_test
      PREVIEW_MODE: true
      GOV_UK_NOTIFY_DEFAULT_API_KEY:
        from_secret: NOTIFY_API_KEY
      GOV_UK_NOTIFY_DEFAULT_TEMPLATE_ID: 2d2a640b-db7f-4eb8-8b41-e5d75fc64b64
      IMAGE_URL: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/forms-runner
    when:
      event:
        - promote
  - name: slack-notification-runner-deployed
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: stp-formbuilder-alerts
      template: >
        {{#success build.status}}
          runner deployment successful. Good job.
          Environment: {{DRONE_DEPLOY_TO}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{else}}
          runner deployment failed. Fix me please.
          Environment: {{DRONE_DEPLOY_TO}}
          Author: {{build.author}}
          Link: {{build.link}}
        {{/success}}
    when:
      status:
        - success
        - failure
    depends_on:
      - deploy-runner        
---
kind: pipeline
name: designer
type: kubernetes

platform:
  os: linux
  arch: amd64
steps:
  - name: deploy-designer
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - apk add -U curl git
      - git fetch origin
      - git reset --hard origin/$${BRANCH}
      - git checkout $${BRANCH}
      - bin/designer/run.sh
    environment:
      ACTION: deploy
      BRANCH: main
      IMAGE_URL: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/stp/forms-designer
      KUBE_TOKEN_ACP_NOTPROD:
        from_secret: forms-designer-kube-token
      PREVIEW_MODE: true
      PREVIEW_URL: https://runner-preview.dev.stp-forms-notprod.homeoffice.gov.uk
      PUBLISH_URL: https://runner-preview.dev.internal.stp-forms-notprod.homeoffice.gov.uk
    when:
      event:
        - promote
  - name: slack-notification-designer-deployed
      image: plugins/slack
      settings:
        webhook:
          from_secret: slack_webhook
        channel: stp-formbuilder-alerts
        template: >
          {{#success build.status}}
            designer deployment successful. Good job.
            Environment: {{DRONE_DEPLOY_TO}}
            Author: {{build.author}}
            Link: {{build.link}}
          {{else}}
            designer deployment failed. Fix me please.
            Environment: {{DRONE_DEPLOY_TO}}
            Author: {{build.author}}
            Link: {{build.link}}
          {{/success}}
      when:
        status:
          - success
          - failure
      depends_on:
        - deploy-designer