---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-network-policy-external-{{ .NAME }}
spec:
  podSelector:
    matchLabels:
      name: {{ .NAME }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-external
      ports:
        - protocol: TCP
          port: {{ .PORT }}
